  spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      url: jdbc:mysql://localhost:3306/search_engine
      password: testtest
    data:
      jpa:
        repositories:
          enabled: true
    jpa:
      hibernate:
        ddl-auto: update
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
  hibernate:
    order_updates: true
    jdbc:
      batch_size: 1000
    order_inserts: true

  config:
    adminLogin: admin
    adminPassword: admin
    webInterface: /admin
    prefix: web
    sites:
     -
       url: http://www.playback.ru
       name: PlayBack.ru
     -
       url: http://radiomv.ru
       name: Radio MV
     -
       url: https://dimonvideo.ru
       name: Димон
     -
       url: https://ipfran.ru/
       name: Федеральный исследовательский центр
     -
       url: https://nikoartgallery.com/
       name: Nico
     -
       url: https://www.svetlovka.ru/
       name: Светловка

    userAgent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
